baseurl = "https://www.justinnuwin.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 10
googleAnalytics = "G-YWJYYVFQXF"

[params]
  contentTypeName = "experience"
  themeColor = "green"
  showMenuItems = 6
  fullWidthTheme = false
  centerTheme = true
  # singlePageSite moves pages from the main nav menu to sections on the homepage.
  # These only menu items with a url starting with "/#" will be displayed using the
  # front matter defined in "homepage/". A collection is displayed for other menu items.
  singlePageSite = true
  homepagePaginateCount = 2

[params.twitter]
  creator = "@justinnuwin"
  site = "@justinnuwin"

[languages]
  [languages.en]
    title = "Justin Nguyen / Software Engineer"
    subtitle = "Justin Nguyen's Portfolio"
    keywords = "software developer big data big-data bigdata machine learning signal processing python c c++ c/c++ git github computer vision data mangement data-mangement embedded systems architect hardware projects portfolio cubesats satellites space"
    copyright = "© 2020 Justin Nguyen"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Justin Nguyen / Software Engineer"
      logoSplit = " / "   # Places logo text blocks in to spans so they wrap nicely
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/#about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "/#skills"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "experience"
        name = "Experience"
        url = "/experience"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "education"
        name = "Education"
        url = "/#education"
        weight = 5
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/#contact"
        weight = 6

