baseurl = "https://justinnuwin.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 2

[params]
  contentTypeName = "experience"
  themeColor = "green"
  showMenuItems = 6
  fullWidthTheme = false
  centerTheme = true
  singlePageSite = true
  # Single page sites moves pages from the main menu to sections on the home page
  # These sections are ordered following the menu order. The collection is displayed
  # as "post" archetypes for the menu item with an identifier matching contentTypeName.

[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Justin Nguyen / Software Engineer"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/#about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "/#skills"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "experience"
        name = "Experience"
        url = "/#experience"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "education"
        name = "Education"
        url = "/#education"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/#contact"
        weight = 5
      [[languages.en.menu.main]]
        identifier = "portfolio"
        name = "Portfolio"
        url = "/portfolio"

